In [3]:
import tensorflow as tf 


In [4]:
from tensorflow.keras.preprocessing.text import one_hot 

In [24]:
sent = ['the glass of dud','the i AM Sherpa','Welcom to my home','One pecie is good cartoon']

In [25]:
sent

['the glass of dud',
 'the i AM Sherpa',
 'Welcom to my home',
 'One pecie is good cartoon']

In [26]:
vocab_size = 500

In [32]:
onehotrep= [one_hot(word,vocab_size) for word in sent]  # value ranges between 0 - 500,larger the better 

In [30]:
# Now the size of the length is different is issue 
# solution is padding : pre padding 

In [31]:
import numpy as np 

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehotrep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 469  28 397 111]
 [  0   0   0   0 469 207 418 201]
 [  0   0   0   0  80 453 447 280]
 [  0   0   0 468 100 259 170 420]]


In [36]:
## 10 feature dimesnions
dim=10

In [38]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [39]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [41]:
##'the glass of dud',
embedded_docs[0]

array([  0,   0,   0,   0, 469,  28, 397, 111], dtype=int32)

In [42]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 356ms/step


array([[ 0.03740288,  0.02825699,  0.04010752,  0.00886543,  0.01602744,
        -0.0146568 , -0.00649637,  0.02796901,  0.04211906,  0.01060031],
       [ 0.03740288,  0.02825699,  0.04010752,  0.00886543,  0.01602744,
        -0.0146568 , -0.00649637,  0.02796901,  0.04211906,  0.01060031],
       [ 0.03740288,  0.02825699,  0.04010752,  0.00886543,  0.01602744,
        -0.0146568 , -0.00649637,  0.02796901,  0.04211906,  0.01060031],
       [ 0.03740288,  0.02825699,  0.04010752,  0.00886543,  0.01602744,
        -0.0146568 , -0.00649637,  0.02796901,  0.04211906,  0.01060031],
       [ 0.02765976, -0.04348774, -0.01168207, -0.02341995,  0.00314077,
        -0.04542744, -0.02603799, -0.02794515, -0.02652247,  0.00631015],
       [ 0.00112586,  0.00339755, -0.0065472 ,  0.01867275,  0.01246948,
         0.00289349,  0.03912527,  0.02739287, -0.0030725 ,  0.00875843],
       [-0.00274277, -0.01344056,  0.01095029, -0.02185522,  0.00201272,
         0.01220776,  0.03772581,  0.00437812