In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# Sentences :boy

sentences = ['the glass of milk','the glass of juice','the cup of tea','I am a good boy','I am good dev']
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good dev']

In [4]:
# Intialize Vocab Size 
voc_size = 10000

In [7]:
# One hot representation:
onehot_rep = [one_hot(words,voc_size) for words in sentences]
onehot_rep  # We get the index based on voc size of that particular word or value!

[[599, 2485, 3442, 1703],
 [599, 2485, 3442, 4527],
 [599, 8218, 3442, 3273],
 [4908, 3754, 9361, 4470, 9356],
 [4908, 3754, 4470, 7724]]

In [11]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences # to maintain lengt or same size
from tensorflow.keras.models import Sequential 

In [13]:
import numpy as np

In [18]:
sent_length = 8 
embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs) # maintain length here 

[[   0    0    0    0  599 2485 3442 1703]
 [   0    0    0    0  599 2485 3442 4527]
 [   0    0    0    0  599 8218 3442 3273]
 [   0    0    0 4908 3754 9361 4470 9356]
 [   0    0    0    0 4908 3754 4470 7724]]


In [19]:
dim = 10 # featurize rep

In [24]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.predict(embedded_docs)

array([[[-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038],
        [-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038],
        [-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038],
        [-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038],
        [-0.00989958,  0.02181285, -0.03280171,  0.04818128,
          0.01999259,  0.00400541, -0.01389667, -0.02746763,
          0.01942035,  0.04238936],
        [ 0.02809941,  0.03457029,  0.04270596, -0.00119598,
         -0.04563823, -0.02028884, -0.04380138,  0.02303128,
         -0.04459411,  0.03107376],
        [-0.01466174,  0.00821022,  0.02530778, -0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,  599, 2485, 3442, 1703], dtype=int32)

In [27]:
model.predict(embedded_docs[0]) # converted into 10 vectors

array([[[-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038]],

       [[-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038]],

       [[-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038]],

       [[-0.00528047,  0.02830572,  0.00341911, -0.02780413,
          0.04970921,  0.00687839, -0.04078348,  0.0356315 ,
         -0.03546072, -0.04897038]],

       [[-0.00989958,  0.02181285, -0.03280171,  0.04818128,
          0.01999259,  0.00400541, -0.01389667, -0.02746763,
          0.01942035,  0.04238936]],

       [[ 0.02809941,  0.03457029,  0.04270596, -0.00119598,
         -0.04563823, -0.02028884, -0.04380138,  0.02303128,
         -0.04459411,  0.03107376]],

       [[-0.01466174,  0.00821022,  0.02